name: Bug Report
description: Report a reproducible bug.
body:
  - type: textarea
    attributes:
      label: Bug description
      description: What is the bug? What is the expected behavior? Feel free to add screenshots too.
      placeholder: Describe the bug here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug? What steps did you take?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: markdown
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: Which version of the package are you using?
      placeholder: v1.2.3
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: What environment are you running in? (OS, PHP version, etc.)
      placeholder: |
        - OS: 
        - PHP version: 
        - ...
      value: |
        - OS: 
        - PHP version: 
        - ...
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: If you have any logs or error output, please paste it here.
      render: shell
  - type: textarea
    attributes:
      label: Additional details
      description: Anything else we should know?